# Generated by Django 4.1.5 on 2023-01-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='About',
            field=models.TextField(default='Coming soon'),
            preserve_default=False,
        ),
    ]
